### ISSUE TITLE
프로젝트 파일이 열리지 않아요..

### ISSUE THREAD

**Issue by yagom** [TutorDot/TutorDot_iOS#4]
@inddoni 인정님 요청으로 코드리뷰를 하기위해 master 저장소를 clone 했는데요, 프로젝트가 열리지 않아요. 확인부탁드립니다. 코드를 보는 것 외에도 제가 실행해 볼 수 있으면 좋겠는데, 실행할 수 있는 환경이 될까요? @sophryu99

**Comment by inddoni** [comment]
야곰님 메일을 이제 확인했네요 ㅠㅠ
컨플릭트가 해결되지 않은 파일이 올라가 있었나봐요!
해결 후 다시 푸시 했습니다!

마스터 클론 받으신 후 pod install 하시면 실행 될 거에요!
앱 테스트 해보실 때, 로그인 아이디는 s99@gmail.com 비밀번호는 s 사용하시면 됩니다!!
바쁘신 중에 정말 감사드립니다!!

2020년 8월 19일 (수) 오후 3:39, yagom <notifications@github.com>님이 작성:
